import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Mint from "../components/Mint";
import ViewNFT from "../components/ViewNFT";
import useNfts from "@/hooks/useNfts";
import { useAccount } from "wagmi";

export default function Home() {
  const { hasMinted } = useNfts();
  const { address, isConnected } = useAccount();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ margin: "6rem", maxWidth: "80%" }}>
          {/* <div className="text-center">
            <h1 className="text-4xl font-bold tracking-tight text-black sm:text-6xl">
              unsere NFT Membership
            </h1>
            <p className="mt-6 text-lg leading-8 text-black">
              Das wom3n.NFT ist auf 50 NFTs limitiert. Wenn deine Wallet auf
              unserer Allowlist steht, kannst du hier dein persönliches NFT
              minten.
            </p>
          </div> */}
          {address && isConnected && hasMinted && (
            <div className="text-center">
              <ViewNFT />
            </div>
          )}
          <div className={styles.center}>
            <Mint />
          </div>
        </div>
      </main>
    </>
  );
}
